### ISSUE TITLE
Containers and VMs label

### ISSUE THREAD

**Issue by gianmarcomennecozzi** [aau-network-security/haaukins-api#10]
provided different label for docker containrs and run VM. Cause when we run the `clean-up` all containers and vms will be closed, no matters if haaukins or APIs ones.

I think we have to change the source code in Haaukins.
I am actually using this branch for the API https://github.com/aau-network-security/haaukins/tree/apipurpose

**Comment by gianmarcomennecozzi** [comment]
@mrturkmencom any suggestion of how to do that?

**Comment by mrturkmencom** [comment]
@gianmarcomennecozzi , I have created a pull request for it (https://github.com/aau-network-security/haaukins/pull/437/commits/907b751c0d64d8c0982de9044287eaacf71088a2), once you have merged and update from go.mod file on haaukins-api repo, clean-up sccript will not effect haaukins-api  and vice versa. 
The important note here is that you should not run the API as user where haaukins is also run. It means that if you run Haaukins with user `ahmet`, you should not run haaukins-api  as user `ahmet`. 
Additional checks and improvements could be done, when you check it let me know .

**Comment by mrturkmencom** [comment]
Related changes have been merged to branch `apipurposes` on main haaukins repo, with commit id https://github.com/aau-network-security/haaukins/commit/265717817af8832c2a5352617769cc49ac61bf3d, when it is tested, this issue could be closed @gianmarcomennecozzi

**Comment by gianmarcomennecozzi** [comment]
i have upgraded the go modules and it should works. you can check it out on this commit https://github.com/aau-network-security/haaukins-api/pull/12/commits/5a0f541d439fa321f0ba1fbfefe62211cd10b19d

**Comment by mrturkmencom** [comment]
Not an issue anymore.
